# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.3
yarn_mappings=26.3+build.2
loader_version=0.19.5

#Fabric api
fabric_version=0.161.0+26.3

# Mod Properties
mod_version = 1.4.0
maven_group = com.ishland
archives_base_name = rsls

curseforge_minecraft_versions=26.3
modrinth_minecraft_versions=26.3
